### ISSUE TITLE
JSONDecodeError in Reef 

### ISSUE THREAD

**Issue by debuggercz** [TheJJ/ceph-balancer#30] opened 2023-10-29 15:27 UTC
Hi.

We are having trouble using the balancer on the Reef version; it throws an error in decoding JSON from 'ceph osd dump --format json,' but the output of this command is valid JSON. Do you know where the issue might be?

```
root@app001 ~/ceph-balancer # git pull
Updating 1c90248..b48ffbf
Fast-forward
 placementoptimizer.py | 2453 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------
 1 file changed, 2089 insertions(+), 364 deletions(-)
root@app001 ~/ceph-balancer # ./placementoptimizer.py balance
Traceback (most recent call last):
  File "/root/ceph-balancer/./placementoptimizer.py", line 5060, in <module>
    exit(main())
  File "/root/ceph-balancer/./placementoptimizer.py", line 5024, in main
    state = ClusterState(args.state, osdsize_method=osdsize_method)
  File "/root/ceph-balancer/./placementoptimizer.py", line 592, in __init__
    self.load(statefile)
  File "/root/ceph-balancer/./placementoptimizer.py", line 619, in load
    osd_dump=jsoncall("ceph osd dump --format json".split()),
  File "/root/ceph-balancer/./placementoptimizer.py", line 274, in jsoncall
    return json.loads(rawdata.decode())
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 2365 (char 2365)
root@app001 ~/ceph-balancer # ceph version
ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)
root@app001 ~/ceph-balancer # python --version
Python 3.9.17
```

Thanks
Michal

**Comment by TheJJ** [comment] 2023-10-29 17:26
Can you please send me the output of `ceph osd dump --format json`? It seems it's not json :) You can send a mail to jj at sft.lol

**Comment by TheJJ** [comment] 2023-10-30 12:29
It appears to be caused by `inf` used as invalid json values...

```json
"read_balance":
{"score_acting":inf,
"score_stable":inf,
"optimal_score":0,
"raw_score_acting":3,
"raw_score_stable":3,
"primary_affinity_weighted":0.99999600648880005,
"average_primary_affinity":1,
"average_primary_affinity_weighted":1}
```

Hmm, it should probably be fixed in upstream-ceph, but we can hopefully hack around this bug somehow.
Python's json parser doesn't allow `inf`, it just accepts `Infinity`, so my first attempt in dc654ec86e2e25df88b976117b1e79d24eb976cf is to just convert the value...

Can you please test and send me `placementoptimizer.py gather yourfile.xz` also via mail? then i can see if reef produces more funny output which I haven't tested so far (don't have a reef cluster yet :))

**Comment by TheJJ** [comment] 2024-02-14 11:12
dc654ec86e2e25df88b976117b1e79d24eb976cf seems to be good enough, but it would of course be better if ceph emitted compliant json... but I think its ok for now. Thanks for the state dump again!

**Closed by TheJJ** 2024-02-14 11:12 UTC
Labels: bug
